import type { Metadata } from "next";
import { Inter, Zilla_Slab } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const sansSerif = Inter({ subsets: ["latin"], variable: "--font-sans-serif" });
const serif = Zilla_Slab({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-serif",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(" font-sans-serif", sansSerif.variable, serif.variable)}
      >
        {children}
      </body>
    </html>
  );
}
